* monoconfig

=monoconfig= is a makefile that:

+ can install every one of Matt's config files in one command
+ works on any one of Matt's (many) machines

This makefile is not built for anyone else to use.  However, if by
some chance you do find anything in this repo helpful, please feel
free to use it.

* Features

+ =m4= and =gpg= for injecting secrets into config files
+ the hostname determines which machine-specific config gets installed
+ the installed config files are write-only
+ non-installable config (such as =emacs= customizes) gets backed up
  automatically in this repository
+ abstract configuration featuring general and host-specific
  components

* Quickstart

#+begin_example
  $ cd /path/to/this/repo
  $ make
#+end_example

* Semi-stateless Lifestyle

=monoconfig= encourages the following semi-stateless lifestyle:

+ your home directory contains a dedicated subdirectory; call it
  =data=
+ every file you might want to open, edit, or back up, including this
  repository, lives in =~/data=
+ everything else on your system, including the contents of =~= that
  are not in =~/data=, is to be treated as disposable, because it can
  be reinstalled

Never again live in fear of blowing away your home directory.  As long
as =~/data= is backed up, you are backed up; all else is ephemera
whose only reason for existing is that you ran an app.

* Background

Once, when I was younger, I bought a new laptop and decided to put
Linux on it.  Boy, oh boy, did that not work.  I decided to learn
Linux in order to make it work, which was a real black diamond of a
learning curve.

It's a foregone conclusion that once you start using Linux, you're
going to be hacking on config files.  And so I hacked, endlessly, for
fourteen years, before realizing that I'd been living in a fog of
primordial dread.  A special hell of my own making, which took the
form of config files, edited in place, thousands of times over
thousands of hours, scattered all over my filesystem, across more than
ten different hosts, *with nothing version controlled*.

It was time to put everything in one place, forever.
