#!/bin/sh

# log errors
rm -f /tmp/xinitrc.log
exec 2>/tmp/xinitrc.log

# trace your code
set -x

# turn off bell
xset b off

# get fonts inta whack
xset fp rehash

# dunst
dunst &
NOTIFY=notify-send
FAILED=$(systemctl --no-legend --no-pager --failed | awk '{print $1}')
if [ "$FAILED" != "" ]
then $NOTIFY -a systemd -u critical "systemd failures" "$FAILED"
fi

# keybindings for X session
xbindkeys

# compositor
picom -b -c

# fire herbst up
exec herbstluftwm -l
