#!/bin/sh

# dunst
dunst &
NOTIFY=notify-send
FAILED=$(systemctl --no-legend --no-pager --failed | awk '{print $1}')
if [ "$FAILED" != "" ]
then $NOTIFY -a systemd -u critical "systemd failures" "$FAILED"
fi

# compositor
picom -b -c

# nm-applet for authentication to UChicago VPN
nm-applet &

