#!/usr/bin/zsh

if [ ! -n "$SSH_CLIENT" ]
then eval (ssh-agent)
     ssh-add
     gpg -d --pinentry-mode loopback dummy.gpg
     # while not gpg -d --pinentry-mode loopback dummy.gpg 1> /dev/null 2>&1 ; : ; end
     emacs --daemon
else :
fi
