;; TODO: mli-p is not working yet
(defun mli-p (path)
  (and (not (file-directory-p path))
       (or (equal (file-name-extension path) "mli")
	 (equal (file-name-extension path) "shutoffmli"))))

(defun mli-dired-toggle ()
  (interactive)
  (let* ((old-path (dired-get-filename))
	 (old-filename (file-name-sans-extension old-path))
	 (old-extension (file-name-extension old-path))
	 (new-extension (cond ((equal old-extension "mli") "shutoffmli")
			      ((equal old-extension "shutoffmli") "mli")
			      (t old-extension)))
	 (new-path (file-name-with-extension old-filename new-extension)))
    (if (equal old-extension new-extension)
	(message "Not an .mli file.")
      (rename-file old-path new-path)
      (revert-buffer))))
