(defun mli-dired-toggle ()
  (let* ((old-path (dired-get-filename))
	 (old-filename (file-name-sans-extension old-path))
	 (old-extension (file-name-extension old-path))
	 (new-extension (cond ((equal old-extension "mli") "shutoffmli")
			      ((equal old-extension "shutoffmli") "mli")
			      (t old-extension)))
	 (new-path (file-name-with-extension old-filename new-extension)))
    (progn (rename-file old-path new-path)
	   (revert-buffer))))
